force-app/main/default/objects/Broker__c/Broker__c.object-meta.xml
<CustomObject>
    <label>Broker</label>
    <nameField>
        <label>Broker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Favorite__c/Favorite__c.object-meta.xml
<CustomObject>
    <label>Favorite</label>
    <nameField>
        <displayFormat>F-{00000000}</displayFormat>
        <label>Favorite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Favorites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Favorite__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Favorites</relationshipLabel>
    <relationshipName>Favorites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LeadAssociation__c/LeadAssociation__c.object-meta.xml
<CustomObject>
    <label>LeadAssociation</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>LeadAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LeadAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Baths__c.field-meta.xml
<CustomField>
    <fullName>Baths__c</fullName>
    <label>Baths</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Listing</fullName>
            </value>
            <value>
                <fullName>Listed</fullName>
            </value>
            <value>
                <fullName>Under Contract</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DreamhouseTests.cls
@IsTest
public class DreamhouseTests {
  static testMethod void testController() {
    DreamHouseSampleDataController.deleteAll();
    System.assertEquals(0, [SELECT COUNT() FROM favorite__c]);
    System.assertEquals(0, [SELECT COUNT() FROM favorite__c]);
    System.assertEquals(0, [SELECT COUNT() FROM property__c]);
    System.assertEquals(0, [SELECT COUNT() FROM broker__c]);
    System.assertEquals(0, [SELECT COUNT() FROM LeadAssociation__c]);
    System.assertEquals(0, [SELECT COUNT() FROM Lead WHERE company = 'Dreamhouse']);
  }

  static testMethod void testGetPropertiesApexController() {
    Property__c p1 = new Property__c(Name = 'Prop 1', Beds__c = 2, Baths__c = 2, Price__c = 1000);
    Property__c p2 = new Property__c(Name = 'Prop 2', Beds__c = 2, Baths__c = 2, Price__c = 2000);
    insert p1;
    insert p2;

    PageReference pref = Page.Similar_Properties;
    pref.getParameters().put('id', p1.id);
    Test.setCurrentPage(pref);

    ApexPages.StandardController con = new ApexPages.StandardController(p1);
    GetPropertiesApexController ext = new GetPropertiesApexController(con);
    System.assertEquals(1, ext.getProperties().size());
  }

  static testMethod void testGetSimilarProperties() {
    Id recordId = 'a0341000002670mAAA';
    String searchCriteria = 'Price';
    Decimal beds = 3;
    Decimal price = 500000;
    Decimal priceRange = 100000;
    MyPropertyController.getSimilarProperties(recordId, searchCriteria, beds, price, priceRange);

    recordId = 'a0341000002670mAAA';
    searchCriteria = 'Bedrooms';
    beds = 4;
    price = 600000;
    priceRange = 50000;
    MyPropertyController.getSimilarProperties(recordId, searchCriteria, beds, price, priceRange);
  }

  static testMethod void testDreamhouseProspects() {
    Lead l = new Lead(LastName = 'the Bear', Company = 'Dreamhouse');
    insert l;
    DreamhouseProspects dhp = new DreamhouseProspects();
    System.assertEquals(1, dhp.getLeads().size());
    dhp.sortList();
    dhp.sortOrder = 'LastName';
    System.assertEquals(1, dhp.getLeads().size());
    //List<Lead> leads = dhp.getLeads();
  }

  static testMethod void testPickListController() {
    String objObject = 'Property__c';
    String fld = 'Status__c';
    PickListController.getPickListValuesIntoList(objObject, fld);
  }
}